language: ruby
rvm:
- 2.5.1
services:
- mysql
before_script:
- cp SIGS/config/database.yml.travis SIGS/config/database.yml
- mysql -e 'create database myapp_test;' -u root
branches:
  only:
  - "/.*/"
script:
- cd SIGS
- bundle install
- bundle exec rake db:load_config
- bundle exec rake db:create
- bundle exec rake db:migrate
- rake cucumber
- bundle exec rspec
- rubocop
after_sucess:
- coveralls push
deploy:
  provider: heroku
  app: sigs-staging
  api_key:
    secure: $HEROKU_API_KEY_STAGING 
  on:
    branch: develop
  run: rails db:seed
