language: ruby
rvm:
- 2.5.1
services:
- mysql
before_script:
- cp SIGS/config/database.yml.travis SIGS/config/database.yml
- mysql -e 'create database myapp_test;' -u root
branches:
  only:
  - "/.*/"
script:
- echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
- cd SIGS
- bundle install
- bundle exec rake db:load_config
- bundle exec rake db:create
- bundle exec rake db:migrate
- rake cucumber
- bundle exec rspec
- rubocop
after_sucess:
- coveralls push
deploy:
  # Deploy develop on the staging environment
  - provider: script
    script: bash script/staging-deploy.sh
    on:
      branch: develop
  # Deploy master on the production environment
  - provider: script
    script: bash script/staging-deploy.sh
    on:
      branch: master
